main = ".open-next/worker.js"
name = "skakatur-dev"
compatibility_date = "2025-10-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = true
