main = ".open-next/worker.js"
name = "skakatur-dev"
compatibility_date = "2026-01-06"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = true

[[routes]]
pattern = "skakatur.dev"
zone_name = "skakatur.dev"
custom_domain = true

[vars]
NEXT_PUBLIC_BASE_URL = "https://skakatur.dev"
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAABunVtq2F8mV8IF1"
